---
- name: Provisioning Control host
  hosts: mgm

  tasks:
  - name: Put ssh privat key
    ansible.builtin.copy:
      src: $HOME/.ssh/id_ed25519
      dest: $HOME/.ssh/id_ed25519
      force: true
      owner: ubuntu
      group: ubuntu
      mode: '0600'
  - name: Add ansible repo
    ansible.builtin.shell:
      cmd: sudo apt-add-repository ppa:ansible/ansible
  - name: Update package manager
    ansible.builtin.shell:
      cmd: apt update
  - name: Install Ansible
    ansible.builtin.package:
      name: ansible
      state: present
